---
- name: Fetch and unarchive UniFi Controller source
  ansible.builtin.unarchive:
    src: "{{ unifi_controller_src_url }}"
    dest: "{{ _temp_dir_raw.path }}"
    remote_src: yes
    owner: ubnt
    group: ubnt

- name: Create 'data' directory
  ansible.builtin.file:
    path: "/var/opt/UniFi/data"
    state: directory
    mode: '0755'
    owner: ubnt
    group: ubnt

- name: Move application directory to '/opt'
  ansible.builtin.shell: |
    mv {{ _temp_dir_raw.path }}/UniFi /opt
    mv UniFi unifi-{{ unifi_controller_version }}
  args:
    chdir: /opt
    creates: "{{ unifi_controller_install_path }}"

- name: Set permissions
  ansible.builtin.file:
    path: "{{ path }}"
    owner: ubnt
    group: ubnt
    mode: '0755'
  loop:
    - "{{ unifi_controller_install_path }}"
    - "{{ unifi_controller_data_path }}"
  loop_control:
    loop_var: path

- name: Symlink versioned install path to vanity path
  ansible.builtin.file:
    src: "{{ unifi_controller_install_path }}"
    dest: "{{ unifi_controller_vanity_install_path }}"
    owner: ubnt
    group: ubnt
    state: link

- name: Symlink data directory to install data path
  ansible.builtin.file:
    src: "{{ unifi_controller_data_path }}"
    dest: "{{ unifi_controller_vanity_install_path }}/data"
    owner: ubnt
    group: ubnt
    state: link
...