---
- name: Include Red Hat specific variables
  when: ansible_os_family == "RedHat"
  ansible.builtin.include_vars: "RedHat.yml"

- name: Include Debian specific variables
  when: ansible_os_family == "Debian"
  ansible.builtin.include_vars: "Debian.yml"

- name: Include Red Hat specific setup tasks
  when: ansible_os_family == "RedHat"
  include_tasks: "setup-RedHat.yml"

- name: Include Debian specific setup tasks
  when: ansible_os_family == "Debian"
  include_tasks: "setup-Debian.yml"

- name: Resolve UniFi install state
  include_tasks: "resolve-install-state.yml"

- name: Include tasks to create system user and group
  include_tasks: "user.yml"

- name: Include pre-tasks
  include_tasks: "pre-tasks.yml"

- name: Include UniFi Network Application deploy tasks
  include_tasks: "install.yml"

- name: Include UniFi Network Application firewalld tasks
  when: _firewalld_status.stat.exists
  include_tasks: "configure-firewalld.yml"

- name: include post-tasks
  include_tasks: "post-tasks.yml"
