---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific setup tasks
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Include pre-tasks
  include_tasks: "pre-tasks.yml"

- name: Include UniFi Controller deploy tasks
  include_tasks: "deploy-unifi-controller.yml"

- name: Include UniFi Controller firewalld tasks
  include_tasks: "configure-firewalld.yml"
  when: _firewalld_status.stat.exists

- name: include post-tasks
  include_tasks: "post-tasks.yml"
