---
# handlers file for unifi-controller

- name: restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted

- name: reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: restart unifi controller
  ansible.builtin.systemd:
    name: unifi
    state: restarted