---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  tasks:
    - name: This is just a shim
      ansible.builtin.debug:
        msg: "This 'default' scenario is just a shim. You should specify a scenario to test this role."
